//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MFC
{
    using System;
    using System.Collections.Generic;
    
    public partial class Applications
    {
        public int id { get; set; }
        public string Appointment { get; set; }
        public string Data { get; set; }
        public string Сonfirmed { get; set; }
        public string Rejected { get; set; }
    
        public virtual Main Main { get; set; }
    }
}
