//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MFC
{
    using System;
    using System.Collections.Generic;
    
    public partial class Jobs
    {
        public int id { get; set; }
        public string Resume { get; set; }
        public string Terms { get; set; }
        public string Demand { get; set; }
    
        public virtual Main Main { get; set; }
    }
}
