//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MFC
{
    using System;
    using System.Collections.Generic;
    
    public partial class Main
    {
        public int id { get; set; }
        public string MFC { get; set; }
        public string Why { get; set; }
        public string Advantages { get; set; }
    
        public virtual Contacts Contacts { get; set; }
        public virtual Jobs Jobs { get; set; }
        public virtual Services Services { get; set; }
    }
}
