//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MFC
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class MFCEntities2 : DbContext
    {
        public MFCEntities2()
            : base("name=MFCEntities2")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<Applications> Applications { get; set; }
        public virtual DbSet<Contacts> Contacts { get; set; }
        public virtual DbSet<Jobs> Jobs { get; set; }
        public virtual DbSet<Main> Main { get; set; }
        public virtual DbSet<Paid> Paid { get; set; }
        public virtual DbSet<Services> Services { get; set; }
        public virtual DbSet<Smart> Smart { get; set; }
    }
}
