//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MFC
{
    using System;
    using System.Collections.Generic;
    
    public partial class Services
    {
        public int id { get; set; }
        public string List { get; set; }
        public string Responsibility { get; set; }
    
        public virtual Main Main { get; set; }
        public virtual Paid Paid { get; set; }
        public virtual Smart Smart { get; set; }
    }
}
